name: Delte PR branch and gh-pages preview

on:
  pull_request:
    types: [ closed ]

jobs:
  post-merge-cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check if PR branch still exists
        run: |
          [ -n '${{ git ls-remote --heads git@github.com:fynnbe/sandbox.git ${{ github.event.pull_request.head.ref }} }}' ]; exists=$?;
          echo "::set-output name=exists::$exists"
      - name: delete PR branch ${{ github.event.pull_request.head.ref }}
        if: ${{ steps.get_branch.pr_check.exists }}
        run: git push origin --delete ${{ github.event.pull_request.head.ref }}
