name: Delte PR branch and gh-pages preview

on:
  pull_request:
    types: [ closed ]

jobs:
  post-merge-cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check if remote still exists
        id: ls-remote
        run: |
          out=$(git ls-remote --heads origin ${{ github.event.pull_request.head.ref }})
          echo "::set-output name=out::$out"
      - name: delete PR branch ${{ github.event.pull_request.head.ref }}
        if: steps.ls-remote.outputs.out
        run: git push origin --delete ${{ github.event.pull_request.head.ref }}
