name: sync

on:
  push:
    branches: [ main ]

jobs:
  setval:
    runs-on: ubuntu-latest
    outputs:
      outval: ${{ steps.setout.outputs.outval }}

    strategy:
      matrix:
        val: [a, b]

    steps:
    - name: set ${{ matrix.val }}
      id: setout
      run: echo '::set-output name=outval::${{ matrix.val }}'

  getval:
    needs: setval
    runs-on: ubuntu-latest
    steps:
      - run: echo 'outval ${{ needs.setval.outputs.outval }}'
