name: test CI

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test 1
      id: test1
      run: |
        echo "::set-output name=out::lala"
    - name: test 2
      id: test2
      run: |
        echo "::set-output name=out::'lala'"
    - name: test 3
      id: test3
      run: |
        echo "::set-output name=out::"
    - name: test 1-1
      if: contains(steps.test1.out, 'la')
      run: |
        echo run
    - name: test 1-2
      if: "contains(steps.test1.out, 'la')"
      run: |
        echo run
    - name: test 1-1n
      if: contains(steps.test1.out, 'lu')
      run: |
        echo run
    - name: test 1-2n
      if: "contains(steps.test1.out, 'lu')"
      run: |
        echo run
    - name: test 2-1
      if: contains(steps.test2.out, 'la')
      run: |
        echo run
    - name: test 2-2
      if: "contains(steps.test2.out, 'la')"
      run: |
        echo run
    - name: test 2-1n
      if: contains(steps.test2.out, 'lu')
      run: |
        echo run
    - name: test 2-2n
      if: "contains(steps.test2.out, 'lu')"
      run: |
        echo run
    - name: test 3-1
      if: contains(steps.test3.out, 'la')
      run: |
        echo run
    - name: test 3-2
      if: "contains(steps.test3.out, 'la')"
      run: |
        echo run
