name: test CI

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test string
      id: teststring
      run: |
        echo "::set-output name=out::lala"
    - name: testbool
      id: testbool
      run: |
        echo "::set-output name=out::false"
    - name: testempty
      id: testempty
      run: |
        echo "::set-output name=out::"
    - name: run string ${{ steps.teststring.outputs.out }} contains la
      if: contains(steps.teststring.outputs.out, 'la')
      run: echo run
    - name: skip string ${{ steps.teststring.outputs.out }} contains lu
      if: contains(steps.teststring.outputs.out, 'lu')
      run: echo run
    - name: not skiped bool false ${{ steps.testbool.outputs.out }}
      if: steps.testbool.outputs.out
      run: echo run
    - name: skip empty
      if: steps.testempty.outputs.out
      run: echo run
    - name: skip empty contains something
      if: contains(steps.testempty.outputs.out, 'something')
      run: echo run
