name: test CI

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test string
      id: teststring
      run: |
        echo "::set-output name=out::lala"
    - name: testbool
      id: testbool
      run: |
        echo "::set-output name=out::false"
    - name: testempty
      id: testempty
      run: |
        echo "::set-output name=out::"
    - name: run string ${{ steps.teststring.outputs.out }} contains la
      if: contains(steps.teststring.outputs.out, 'la')
      run: echo run
    - name: skip string ${{ steps.teststring.outputs.out }} contains lu
      if: contains(steps.teststring.outputs.out, 'lu')
      run: echo run
    - name: not skiped bool false ${{ steps.testbool.outputs.out }}
      if: steps.testbool.outputs.out
      run: echo run
    - name: skip empty
      if: steps.testempty.outputs.out
      run: echo run
    - name: skip empty contains something
      if: contains(steps.testempty.outputs.out, 'something')
      run: echo run

    - name: check if remote still exists
      id: ls-remote
      run: |
        out=$(git ls-remote --heads origin branch)
        echo "::set-output name=out::$out"

    - name: check if non-existing remote exists
      id: ls-remote-no
      run: |
        out=$(git ls-remote --heads origin nooooooooooo)
        echo "::set-output name=out::$out"

    - name: delete PR branch branch
      if: steps.ls-remote.outputs.out
      run: echo would delete

    - name: delete PR branch nooooooooooooo
      if: steps.ls-remote-no.outputs.out
      run: echo would delete
    