name: main wf

concurrency: main

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
  push:
    branches: [ main ]

jobs:
  only-unmerged-pr-job:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: step for unmerged pr
        run: |
          echo ${{ github.event.pull_request }}

  some-main-job:
    runs-on: ubuntu-latest
    steps:
      - name: gh event name is ${{ github.event_name }}
        run: echo ${{ github.event }}
      - name: echo github.event.pull_request.merged
        run: echo ${{ github.event.pull_request.merged }}
