name: wfA

on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: 'dy run'
        required: true
        default: true
        type: boolean

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, closed ]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.dryrun }}
      - run: echo lala
        if: ${{ github.event.inputs.dryrun }}
      - run: echo lala
        if: github.event.inputs.dryrun
      - run: echo not lala
        if: ${{ !github.event.inputs.dryrun }}
      - run: echo lala True
        if: ${{ github.event.inputs.dryrun == True }}
      - run: echo lala True
        if: github.event.inputs.dryrun == True
      - run: echo lala true
        if: ${{ github.event.inputs.dryrun == true }}
      - run: echo lala true
        if: github.event.inputs.dryrun == true
