name: wfA

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, closed ]

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
    - run: echo lala
