name: wfA

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - name: github.event.number ${{ github.event.number }}
        run: echo here
