name: wfA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, closed ]

jobs:
  some-job:
    uses: fynnbe/sanbox/.github/workflows/wfB.yaml@main
    with:
      message: "my message"
      ref: main
