name: wfA

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, closed ]

jobs:

  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environments/general_1.yaml
        extra-specs: |
          python=${{ matrix.python-version }}
    - run: python scripts/subproc.py --mamba-cmd micromamba
      shell: bash -l {0}
