name: wfA

on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: 'dy run'
        required: true
        default: true
        type: boolean
      conclude:
        description: run conclude job
        required: true
        default: false
        type: boolean

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, closed ]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.dryrun }}
      - run: echo yes
        if: ${{ github.event.inputs.dryrun == 'true'}}
      - run: echo no
        if: ${{ github.event.inputs.dryrun == 'false'}}

  conclude:
    if: always() &amp;&amp; ${{inputs.conclude}}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello ${{string(inputs.conclude)}}'
