name: wfA

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - name: github.event.number ${{ github.event.number }}
        run: echo here
      - name: workflow.event.number ${{ event.number }}
        run: echo here
      - name: context.event.number ${{ context.event.number }}
        run: echo here
      - name: context.github.event.number ${{ context.github.event.number }}
        run: echo here
      - name: context.event_name ${{ context.event_name }}
        run: echo here
