name: wfA

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'env name'
        required: true
        type: string


jobs:

  call:
    uses: fynnbe/sandbox/.github/workflows/wf_call.yaml@main
    with:
      environment: ${{inputs.environment}}
