name: wfB

on:
  workflow_dispatch:
    inputs:
      message:
        description: "a message"
        type: string
        required: true
  workflow_call:
    inputs:
      message:
        description: "a message"
        type: string
        required: true

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - name: github.event.inputs.message ${{ github.event.inputs.message }}
        run: echo here
      - name: inputs.message ${{ inputs.message }}
        run: echo here